---
- id: snykio:go:github.com/kubernetes/kubernetes/staging/src/k8s.io/client-go/discovery/cached/disk:174835
  title: World Writable Files
  description: |
    [github.com/kubernetes/kubernetes/staging/src/k8s.io/client-go/discovery/cached/disk][1]
    is a Production-Grade Container Scheduling and Management

    Affected versions of this package are vulnerable to World Writable
    Files. When using the cached location specified by the `--cache-dir`
    option, all cache files written to this directory are written with
    world-writeable (`rw-rw-rw-`) permissions. The default location of this
    directory is `$HOME/.kube/http-cache`.



    [1]: https://kubernetes.io
  affected_package: github.com/kubernetes/kubernetes/staging/src/k8s.io/client-go/discovery/cached/disk
  vulnerable_versions:
  - ">=1.8.0 <1.12.9"
  severity: low
  package_manager: go
  cve:
  - CVE-2019-11244
  cwe:
  - CWE-276
  disclosed_date: 2019-04-22
  created_date: 2019-04-25
  last_modified_date: 2019-04-25
  credit:
  - jzebor
  references:
  - https://github.com/kubernetes/client-go/commit/790a4f63632139cf6731014d00a9a8338f1fbd7d
  - https://github.com/kubernetes/kubernetes/issues/76676
  - https://github.com/kubernetes/kubernetes/pull/77874
  - https://github.com/kubernetes/kubernetes/pull/77874/commits/f228ae3364729caed59087e23c42868454bc3ff4
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMKUBERNETESKUBERNETESSTAGINGSRCK8SIOCLIENTGODISCOVERYCACHEDDISK-174835
