---
- id: friendsofphp:packagist:magento/product-community-edition:2016-07-19
  title: Unauthenticated crypto and weak IV in Magento\Framework\Encryption
  affected_package: magento/product-community-edition
  vulnerable_versions:
  - ">=2.0 <2.1"
  - ">=2.1 <2.2"
  - ">=2.2 <2.2.6"
  package_manager: packagist
  cve:
  - CVE-2016-6485
  disclosed_date: 2018-06-27
  created_date: 2018-06-27
  last_modified_date: 2018-06-27
  credit:
  - FriendsOfPHP
  references:
  - http://www.openwall.com/lists/oss-security/2016/07/19/3
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/magento/product-community-edition/2016-07-19.yaml
- id: friendsofphp:packagist:magento/product-community-edition:2018-06-27
  title: Magento 2.2.5 and 2.1.14 Security update
  affected_package: magento/product-community-edition
  vulnerable_versions:
  - ">=2.1 <2.1.14"
  - ">=2.2 <2.2.5"
  package_manager: packagist
  disclosed_date: 2018-06-27
  created_date: 2018-06-27
  last_modified_date: 2018-06-27
  credit:
  - FriendsOfPHP
  references:
  - https://magento.com/security/patches/magento-2.2.5-and-2.1.14-security-update
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/magento/product-community-edition/2018-06-27.yaml
- id: friendsofphp:packagist:magento/product-community-edition:2018-09-10
  title: Magento 2.2.6 and 2.1.15 Security update
  affected_package: magento/product-community-edition
  vulnerable_versions:
  - ">=2.1 <2.1.15"
  - ">=2.2 <2.2.6"
  package_manager: packagist
  disclosed_date: 2018-09-10
  created_date: 2018-09-10
  last_modified_date: 2018-09-10
  credit:
  - FriendsOfPHP
  references:
  - https://magento.com/security/patches/magento-2.2.6-and-2.1.15-security-update
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/magento/product-community-edition/2018-09-10.yaml
- id: friendsofphp:packagist:magento/product-community-edition:2018-11-28
  title: Magento 2.2.7 and 2.1.16 Security update. Closes RCE,XSS and other vulnerabilities
  affected_package: magento/product-community-edition
  vulnerable_versions:
  - ">=2.1 <2.1.16"
  - ">=2.2 <2.2.7"
  package_manager: packagist
  disclosed_date: 2018-11-28
  created_date: 2018-11-28
  last_modified_date: 2018-11-28
  credit:
  - FriendsOfPHP
  references:
  - https://magento.com/security/patches/magento-2.2.7-and-2.1.16-security-update
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/magento/product-community-edition/2018-11-28.yaml
- id: friendsofphp:packagist:magento/product-community-edition:CVE-2016-6485
  title: Unauthenticated crypto and weak IV in Magento\Framework\Encryption
  affected_package: magento/product-community-edition
  vulnerable_versions:
  - ">=2.0 <2.1"
  - ">=2.1 <2.2"
  - ">=2.2 <2.2.6"
  package_manager: packagist
  cve:
  - CVE-2016-6485
  disclosed_date: 2018-06-27
  created_date: 2018-06-27
  last_modified_date: 2018-06-27
  credit:
  - FriendsOfPHP
  references:
  - http://www.openwall.com/lists/oss-security/2016/07/19/3
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/magento/product-community-edition/CVE-2016-6485.yaml
- id: snykio:packagist:magento/product-community-edition:72225
  title: Insecure Encryption
  description: |+
    Affected versions of \[magento/product-community-edition\] are
    vulnerable to Insecure Encryption due to unauthenticated crypto and weak
    IV in the `Magento\Framework\Encryption` method.

  affected_package: magento/product-community-edition
  vulnerable_versions:
  - "<2.2.5"
  severity: high
  package_manager: packagist
  cve:
  - CVE-2016-6485
  cwe:
  - CWE-326
  disclosed_date: 2018-07-04
  created_date: 2018-07-19
  last_modified_date: 2018-07-19
  credit:
  - Scott Arciszewski
  references:
  - http://www.openwall.com/lists/oss-security/2016/07/19/3
  source_url: https://snyk.io/vuln/SNYK-PHP-MAGENTOPRODUCTCOMMUNITYEDITION-72225
