version: 2

jobs:
  build-lint-test:
    working_directory: ~/yavdb
    docker:
    - image: circleci/ruby:2.3.7
    steps:
    - checkout

    - name: Install Bundler Version
      type: shell
      command: gem install bundler -v 1.16

    - name: Prepare yavdb cache
      type: shell
      command: echo "$(date)" > /tmp/yavdb.cache.log

    - name: Restore gem cache
      type: cache-restore
      keys:
      - 2-gem-yavdb-{{ checksum "Gemfile.lock" }}
      - 2-gem-yavdb-

    - name: Restore yavdb cache
      type: cache-restore
      keys:
      - 1-crawler-yavdb-cache-{{ checksum "/tmp/yavdb.cache.log" }}
      - 1-crawler-yavdb-cache-

    - name: Bundle Install
      type: shell
      command: bundle install --path /tmp/vendor/bundle

    - name: Save bundler cache
      type: cache-save
      key: 2-gem-yavdb-{{ checksum "Gemfile.lock" }}
      paths:
      - /tmp/vendor/bundle

    - name: Rubocop
      type: shell
      command: bundle exec rubocop

    - name: Tests
      type: shell
      command: bundle exec rake

    - name: Save yavdb cache
      type: cache-save
      key: 1-crawler-yavdb-cache-{{ checksum "/tmp/yavdb.cache.log" }}
      paths:
      - ~/.yavdb/cache

workflows:
  version: 2
  test-and-publish:
    jobs:
    - build-lint-test
