---
- id: snykio:nuget:system.management.automation:451667
  title: Access Restriction Bypass
  description: |
    [System.Management.Automation][1] is a System Management Automation for
    PowerShell.

    Affected versions of this package are vulnerable to Access Restriction
    Bypass. A security feature bypass vulnerability exists in Windows
    Defender Application Control (WDAC) which could allow an attacker to
    bypass `WDAC` enforcement.



    [1]: https://www.nuget.org/packages/System.Management.Automation.dll/
  affected_package: system.management.automation
  vulnerable_versions:
  - ">= 6.1.0 < 6.1.5"
  - ">= 6.2.0 < 6.2.2"
  severity: medium
  package_manager: nuget
  cve:
  - CVE-2019-1167
  cwe:
  - CWE-284
  disclosed_date: 2019-07-19
  created_date: 2019-07-21
  last_modified_date: 2019-07-21
  credit:
  - Unknown
  references:
  - https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-1167
  source_url: https://snyk.io/vuln/SNYK-DOTNET-SYSTEMMANAGEMENTAUTOMATION-451667
