---
- id: nodesecurity:npm:eslint-config-eslint:2018-07-12
  title: Malicious package
  description: Version 5.0.2 of `eslint-config-eslint` was published without authorization
    and was found to contain malicious code. This code would read the users `.npmrc`
    file and send any found authentication tokens to a remote server.
  affected_package: eslint-config-eslint
  vulnerable_versions:
  - 5.0.2
  patched_versions:
  - "< 5.0.2 || > 5.0.2"
  severity: high
  package_manager: npm
  credit:
  - Eslint Team
  source_url: https://nodesecurity.io/advisories/674
