---
- id: snykio:npm:eslint-config-eslint:72491
  title: Malicious Package
  description: |
    [`eslint-config-eslint`][1] is the ECMAScript scope analyzer used in
    ESLint.

    Version 5.0.2 was identified as malicious after a possible npm account
    takeover. During installation, the malicious code download code from
    `pastebin.com`, then executed it. It sent the contents of the user’s
    `.npmrc` file to the attacker, which typically contains access tokens
    for publishing to npm.

    The malicious package versions have been unpublished from npm.



    [1]: https://www.npmjs.com/package/eslint-scope
  affected_package: eslint-config-eslint
  vulnerable_versions:
  - "=5.0.2"
  severity: high
  package_manager: npm
  cwe:
  - CWE-506
  disclosed_date: 2018-07-12
  created_date: 2018-07-13
  last_modified_date: 2018-07-13
  credit:
  - Unknown
  references:
  - https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes
  - https://github.com/eslint/eslint-scope/issues/39
  source_url: https://snyk.io/vuln/SNYK-JS-ESLINTCONFIGESLINT-72491
