---
- id: ossindex:npm:koa-router-swagger-ui:8399946929
  title: Cross Site Scripting (XSS)
  description: A malicious swagger JSON document can be loaded via the `url` parameter
    in a query, taking advantage of an XSS vulnerability.
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - 2.1.4
  package_manager: npm
  disclosed_date: 2016-07-22
  created_date: 2016-07-22
  last_modified_date: 2017-03-13
  credit:
  - OSSIndex
  references:
  - https://cwe.mitre.org/data/definitions/79.html
  - https://github.com/swagger-api/swagger-ui/issues/1866
  - https://github.com/swagger-api/swagger-ui/pull/1867
  - https://nodesecurity.io/advisories/123
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
- id: ossindex:npm:koa-router-swagger-ui:8399946983
  title: Cross Site Scripting (XSS)
  description: Property names are not escaped and allow XSS, by providing a schema
    file with a malicious property.
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - "<=2.2.0"
  package_manager: npm
  disclosed_date: 2016-07-22
  created_date: 2016-07-22
  last_modified_date: 2017-03-13
  credit:
  - OSSIndex
  references:
  - https://cwe.mitre.org/data/definitions/79.html
  - https://en.wikipedia.org/wiki/Content_Security_Policy
  - https://github.com/swagger-api/swagger-ui/issues/1865
  - https://nodesecurity.io/advisories/126
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
- id: ossindex:npm:koa-router-swagger-ui:8402377071
  title: XSS via Content-type header
  description: "> By using a malicious server which returns script as the value of
    the Content-Type header, it is possible to execute arbitrary code using the demonstration
    capabilities of Swagger-UI.\n> \n> -- [nodesecurity.io](https://nodesecurity.io/advisories/131)"
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - 2.1.4
  package_manager: npm
  disclosed_date: 2017-01-25
  created_date: 2017-01-25
  last_modified_date: 2017-03-13
  credit:
  - OSSIndex
  references:
  - https://github.com/swagger-api/swagger-ui/issues/1863
  - https://nodesecurity.io/advisories/131
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
- id: ossindex:npm:koa-router-swagger-ui:8402397873
  title: "[Unconfirmed] Cross Site Scripting (XSS)"
  description: HTML is not escaped when the API responds with `text/html`, allowing
    for possible XSS attacks.
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - "<=2.0.21"
  package_manager: npm
  disclosed_date: 2017-02-11
  created_date: 2017-02-11
  last_modified_date: 2017-03-13
  credit:
  - OSSIndex
  references:
  - https://github.com/wordnik/swagger-ui/issues/1154
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
- id: ossindex:npm:koa-router-swagger-ui:8402397897
  title: Fix self XSS in request url.
  description: "> A user who has copy/pasted data from another or has been tricked
    into pasting into the accessToken box could XSS him/herself.\n> \n> -- [github.com](https://github.com/swagger-api/swagger-ui/pull/541)"
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - "<2.0.24"
  package_manager: npm
  disclosed_date: 2017-02-11
  created_date: 2017-02-11
  last_modified_date: 2017-03-13
  credit:
  - OSSIndex
  references:
  - https://cwe.mitre.org/data/definitions/79.html
  - https://github.com/swagger-api/swagger-ui/commit/3a7b66d34565c104e85650439fbc17f89b294e10
  - https://github.com/swagger-api/swagger-ui/issues/541
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
- id: ossindex:npm:koa-router-swagger-ui:8402397918
  title: Cross Site Scripting (XSS) in url parameter
  description: The `url` query parameter can be used for Cross Site Scripting where
    showMessage and onFailure both injected strings straight into the DOM, without
    escaping html entities.
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - 2.1.0-M1
  - 2.1.0-M2
  package_manager: npm
  disclosed_date: 2017-02-11
  created_date: 2017-02-11
  last_modified_date: 2017-07-30
  credit:
  - OSSIndex
  references:
  - https://github.com/swagger-api/swagger-ui/issues/1262
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
- id: ossindex:npm:koa-router-swagger-ui:8402397919
  title: Cross Site Scripting (XSS)
  description: 'A regression in URL parameter escaping. '
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - ">2.1.0 <2.2.1"
  package_manager: npm
  disclosed_date: 2017-02-11
  created_date: 2017-02-11
  last_modified_date: 2017-03-13
  credit:
  - OSSIndex
  references:
  - https://github.com/swagger-api/swagger-ui/commit/a906cffea4550eaa5369e4933a50753213cf09df
  - https://github.com/swagger-api/swagger-ui/issues/1617
  - https://github.com/swagger-api/swagger-ui/pull/2334
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
- id: ossindex:npm:koa-router-swagger-ui:8402398056
  title: Cross Site Scripting (XSS) in message bar
  description: Unescaped HTML is rendered in the message bar, enabling possible cross
    site scripting attacks.
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - ">=2.1.1 <2.1.4"
  package_manager: npm
  disclosed_date: 2017-02-12
  created_date: 2017-02-12
  last_modified_date: 2017-03-13
  credit:
  - OSSIndex
  references:
  - https://github.com/swagger-api/swagger-ui/commit/1945404efef053af688d872da806eec092fac7f0
  - https://github.com/swagger-api/swagger-ui/issues/1530
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
- id: ossindex:npm:koa-router-swagger-ui:8402398059
  title: Cross Site Scripting (XSS)
  description: 'Method description text is not properly escaped, enabling an XSS vulnerability.

'
  affected_package: koa-router-swagger-ui
  vulnerable_versions:
  - "<2.2.1"
  package_manager: npm
  disclosed_date: 2017-02-12
  created_date: 2017-02-12
  last_modified_date: 2017-03-13
  credit:
  - OSSIndex
  references:
  - https://github.com/swagger-api/swagger-ui/commit/a906cffea4550eaa5369e4933a50753213cf09df
  - https://github.com/swagger-api/swagger-ui/issues/1864
  source_url: https://ossindex.net/resource/package/8399534978/vulnerabilities
