---
- id: npmjs:npm:restify-swagger-jsdoc:1037
  title: Path Traversal
  description: "Versions of `restify-swagger-jsdoc` prior to 3.2.1 are vulnerable
    to Path Traversal.  The package fails to properly sanitize URLs, which may allow
    attackers to access server files outside the `swagger-ui` folder by using relative
    paths.  \n"
  affected_package: restify-swagger-jsdoc
  vulnerable_versions:
  - "<3.2.1"
  severity: high
  package_manager: npm
  cwe: CWE-22
  disclosed_date: 1970-01-01
  created_date: 1970-01-01
  last_modified_date: 1970-01-01
  credit: xylesoft
  references: https://npmjs.com/advisories/1037
  source_url: https://npmjs.com/advisories/1037
