---
- id: snykio:rubygems:settingslogic:20413
  title: Man-in-the-Middle (MitM)
  description: |
    [`settingslogic`][1] is a simple and straightforward settings solution
    that uses an ERB enabled YAML file and a singleton design pattern.

    Affected versions of the package are vulnerable to Man-in-the-middle
    (MitM) attacks due to attacks due to downloading gems over an insecure
    protocol. Without a secure connection, it is possible for an attacker to
    intercept this connection and alter the packages received. In serious
    cases, this may even lead to Remote Code Execution (RCE) on your host
    server.

    You can read more about `Man-in-the-Middle (MitM)` on our [blog][2].



    [1]: https://rubygems.org/gems/settingslogic
    [2]: https://snyk.io/blog/https-breaking-through/
  affected_package: settingslogic
  vulnerable_versions:
  - ">=2.0.7"
  severity: medium
  package_manager: rubygems
  cwe:
  - CWE-300
  disclosed_date: 2014-06-01
  created_date: 2017-08-01
  last_modified_date: 2017-08-01
  credit:
  - Justin Grevich
  references:
  - https://github.com/binarylogic/settingslogic/pull/72
  - https://github.com/settingslogic/settingslogic/commit/acb68b8b38f0493688a6ce70db204f26236a0061
  source_url: https://snyk.io/vuln/SNYK-RUBY-SETTINGSLOGIC-20413
