---
- id: snykio:maven:com.ibm:ibm-application-security:460450
  title: Information Exposure
  description: |
    [com.ibm:ibm-application-security][1] is a plugin for executing security
    scans in IBM Application Security on Cloud.

    Affected versions of this package are vulnerable to Information
    Exposure. While the password is stored encrypted on disk, it is
    transmitted in plain text as part of the configuration form. This can
    result in exposure of the password through browser extensions,
    cross-site scripting vulnerabilities, and similar situations.



    [1]: https://github.com/jenkinsci/ibm-asoc-plugin
  affected_package: com.ibm:ibm-application-security
  vulnerable_versions:
  - "< 1.2.5"
  severity: low
  package_manager: maven
  cwe:
  - CWE-200
  disclosed_date: 2019-08-28
  created_date: 2019-08-29
  last_modified_date: 2019-08-29
  credit:
  - IB Boost
  - James Holderness
  references:
  - https://jenkins.io/security/advisory/2019-08-28/
  source_url: https://snyk.io/vuln/SNYK-JAVA-COMIBM-460450
