---
- id: snykio:maven:com.datatheorem.mobileappsecurity.jenkins.plugin:datatheorem-mobile-app-security:469199
  title: Insufficiently Protected Credentials
  description: |
    [com.datatheorem.mobileappsecurity.jenkins.plugin:datatheorem-mobile-app-security][1]
    is a Jenkins plugin to automatically upload builds to Data Theorem.

    Affected versions of this package are vulnerable to Insufficiently
    Protected Credentials. The plugin stores credentials unencrypted in job
    `config.xml` files on the Jenkins master where they could be viewed by
    users with `Extended Read` permission, or access to the master file
    system.



    [1]: https://plugins.jenkins.io/datatheorem-mobile-app-security
  affected_package: com.datatheorem.mobileappsecurity.jenkins.plugin:datatheorem-mobile-app-security
  vulnerable_versions:
  - "< 1.4.0"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2019-10413
  cwe:
  - CWE-312
  disclosed_date: 2019-09-25
  created_date: 2019-09-26
  last_modified_date: 2019-09-26
  credit:
  - IB Boost
  - James Holderness
  references:
  - https://jenkins.io/security/advisory/2019-09-25/
  source_url: https://snyk.io/vuln/SNYK-JAVA-COMDATATHEOREMMOBILEAPPSECURITYJENKINSPLUGIN-469199
