---
- id: snykio:maven:io.jenkins:configuration-as-code:32395
  title: Information Exposure
  description: |
    [io.jenkins:configuration-as-code][1] has been designed as an
    opinionated way to configure jenkins based on human-readable declarative
    configuration files.

    Affected versions of this package are vulnerable to Information Exposure
    via the `ConfigurationAsCode.java` method. An attacker with
    `Overall/Read` access could obtain the `YAML` export of the Jenkins
    configuration.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 0.8-alpha"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2018-1000609
  cwe:
  - CWE-200
  disclosed_date: 2018-06-25
  created_date: 2018-07-01
  last_modified_date: 2018-07-01
  credit:
  - Unknown
  references:
  - https://jenkins.io/security/advisory/2018-06-25/#SECURITY-927
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-32395
- id: snykio:maven:io.jenkins:configuration-as-code:32403
  title: Information Exposure
  description: |
    [io.jenkins:configuration-as-code][1] has been designed as an
    opinionated way to configure jenkins based on human-readable declarative
    configuration files.

    Affected versions of this package are vulnerable to Information Exposure
    attacks. An attacker with access to Jenkins log files could obtain the
    passwords configured using Configuration as Code Plugin.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 0.8-alpha"
  severity: high
  package_manager: maven
  cve:
  - CVE-2018-1000610
  cwe:
  - CWE-200
  disclosed_date: 2018-06-25
  created_date: 2018-07-01
  last_modified_date: 2018-07-01
  credit:
  - Unknown
  references:
  - https://jenkins.io/security/advisory/2018-06-25/#SECURITY-929
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-32403
- id: snykio:maven:io.jenkins:configuration-as-code:456238
  title: Information Exposure
  description: |
    [io.jenkins:configuration-as-code][1] is a plugin for configuring
    Jenkins based on human-readable declarative configuration files.

    Affected versions of this package are vulnerable to Information Exposure
    due to improper masking to values expected to be hidden being applied
    when logging the configuration being applied.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 1.25"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2019-10343
  cwe:
  - CWE-200
  disclosed_date: 2019-07-31
  created_date: 2019-08-01
  last_modified_date: 2019-08-01
  credit:
  - Unknown
  references:
  - https://jenkins.io/security/advisory/2019-07-31/
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-456238
- id: snykio:maven:io.jenkins:configuration-as-code:456239
  title: Information Exposure
  description: |
    [io.jenkins:configuration-as-code][1] is a plugin for configuring
    Jenkins based on human-readable declarative configuration files.

    Affected versions of this package are vulnerable to Information Exposure
    due to proxy password not being treated as a secret to be masked when
    logging or encrypted for export.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 1.25"
  severity: low
  package_manager: maven
  cve:
  - CVE-2019-10345
  cwe:
  - CWE-200
  disclosed_date: 2019-07-31
  created_date: 2019-08-01
  last_modified_date: 2019-08-01
  credit:
  - Unknown
  references:
  - https://jenkins.io/security/advisory/2019-07-31/
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-456239
- id: snykio:maven:io.jenkins:configuration-as-code:456240
  title: Information Exposure
  description: |
    [io.jenkins:configuration-as-code][1] is a plugin for configuring
    Jenkins based on human-readable declarative configuration files.

    Affected versions of this package are vulnerable to Information Exposure
    due to sensitive values expected to be exported in their encrypted form
    not reliably identified.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 1.25"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2019-10363
  cwe:
  - CWE-200
  disclosed_date: 2019-07-31
  created_date: 2019-08-01
  last_modified_date: 2019-08-01
  credit:
  - Unknown
  references:
  - https://jenkins.io/security/advisory/2019-07-31/
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-456240
- id: snykio:maven:io.jenkins:configuration-as-code:456241
  title: Missing Permission Check
  description: |
    [io.jenkins:configuration-as-code][1] is a plugin for configuring
    Jenkins based on human-readable declarative configuration files.

    Affected versions of this package are vulnerable to Missing Permission
    Check. Various HTTP endpoints allow users with Overall/Read access to
    access the generated schema and documentation for this plugin containing
    detailed information about installed plugins.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 1.25"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2019-10344
  cwe:
  - CWE-284
  disclosed_date: 2019-07-31
  created_date: 2019-08-01
  last_modified_date: 2019-08-01
  credit:
  - Mikael Barbero
  references:
  - https://jenkins.io/security/advisory/2019-07-31/
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-456241
- id: snykio:maven:io.jenkins:configuration-as-code:456321
  title: Information Exposure
  description: |
    [io.jenkins:configuration-as-code][1] is a plugin for configuring
    Jenkins based on human-readable declarative configuration files.

    Affected versions of this package are vulnerable to Information Exposure
    due to values not being escaped resulting in variable interpolation
    during configuration import when exporting, allowing attackers with
    permission to change Jenkins system configuration to obtain the values
    of environment variables.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 1.25"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2019-10362
  cwe:
  - CWE-200
  disclosed_date: 2019-07-31
  created_date: 2019-08-01
  last_modified_date: 2019-08-01
  credit:
  - Wadeck Follonier
  references:
  - https://jenkins.io/security/advisory/2019-07-31/
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-456321
