---
- id: snykio:maven:io.jenkins:configuration-as-code:32395
  title: Information Exposure
  description: |
    [io.jenkins:configuration-as-code][1] has been designed as an
    opinionated way to configure jenkins based on human-readable declarative
    configuration files.

    Affected versions of this package are vulnerable to Information Exposure
    via the `ConfigurationAsCode.java` method. An attacker with
    `Overall/Read` access could obtain the `YAML` export of the Jenkins
    configuration.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 0.8-alpha"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2018-1000609
  cwe:
  - CWE-200
  disclosed_date: 2018-06-25
  created_date: 2018-07-01
  last_modified_date: 2018-07-01
  credit:
  - Unknown
  references:
  - https://jenkins.io/security/advisory/2018-06-25/#SECURITY-927
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-32395
- id: snykio:maven:io.jenkins:configuration-as-code:32403
  title: Information Exposure
  description: |
    [io.jenkins:configuration-as-code][1] has been designed as an
    opinionated way to configure jenkins based on human-readable declarative
    configuration files.

    Affected versions of this package are vulnerable to Information Exposure
    attacks. An attacker with access to Jenkins log files could obtain the
    passwords configured using Configuration as Code Plugin.



    [1]: https://github.com/jenkinsci/configuration-as-code-plugin
  affected_package: io.jenkins:configuration-as-code
  vulnerable_versions:
  - "< 0.8-alpha"
  severity: high
  package_manager: maven
  cve:
  - CVE-2018-1000610
  cwe:
  - CWE-200
  disclosed_date: 2018-06-25
  created_date: 2018-07-01
  last_modified_date: 2018-07-01
  credit:
  - Unknown
  references:
  - https://jenkins.io/security/advisory/2018-06-25/#SECURITY-929
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOJENKINS-32403
