---
- id: ossindex:maven:io.swagger:swagger-codegen-project:2017-08-01
  title: Remote Code Execution
  description: "> Maliciously crafted Swagger documents can be used to dynamically
    create HTTP API clients and servers with embedded arbitrary code execution in
    the underlying operating system. This is achieved by the fact that some parsers/generators
    trust insufficiently sanitized parameters within a Swagger document to generate
    a client code base.\n> \n> -- [rapid7.com](https://community.rapid7.com/community/infosec/blog/2016/06/23/r7-2016-06-remote-code-execution-via-swagger-parameter-injection-cve-2016-5641)"
  affected_package: io.swagger:swagger-codegen-project
  vulnerable_versions:
  - "<2.2.0"
  package_manager: maven
  disclosed_date: 2017-08-01
  created_date: 2017-08-01
  last_modified_date: 2017-08-01
  credit:
  - OSSIndex
  references:
  - https://community.rapid7.com/community/infosec/blog/2016/06/23/r7-2016-06-remote-code-execution-via-swagger-parameter-injection-cve-2016-5641
  - https://github.com/swagger-api/swagger-codegen/commit/80666394f671ec38f363732a16ed0fb284fd295c
  - https://github.com/swagger-api/swagger-codegen/pull/3201
  source_url: https://ossindex.net/resource/package/7108612210/vulnerabilities
- id: snykio:maven:io.swagger:swagger-codegen-project:30446
  title: Arbitrary Code Execution
  description: |
    [`io.swagger:swagger-codegen`][1] is a simple yet powerful
    representation of your RESTful API.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution via parameter injection. By leveraging this vulnerability, an
    attacker can inject arbitrary execution code embedded with a client or
    server generated automatically to interact with the definition of
    service.



    [1]: https://swagger.io
  affected_package: io.swagger:swagger-codegen-project
  vulnerable_versions:
  - "< 2.2.0"
  severity: high
  package_manager: maven
  cwe:
  - CWE-94
  disclosed_date: 2016-07-21
  created_date: 2016-07-21
  last_modified_date: 2016-07-21
  credit:
  - Scott Davis
  references:
  - https://community.rapid7.com/community/infosec/blog/2016/06/23/r7-2016-06-remote-code-execution-via-swagger-parameter-injection-cve-2016-5641
  - https://github.com/swagger-api/swagger-codegen/pull/3201
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOSWAGGER-30446
