---
- id: snykio:maven:io.swagger:swagger-parser:CVE-2017-1000207
  title: Arbitrary Code Execution
  description: |
    [`io.swagger:swagger-codegen`][1] is a simple yet powerful
    representation of your RESTful API.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution via the yaml parsing functionality. When a maliciously crafted
    yaml Open-API specification is parsed, it is possible to execute
    arbitrary code on the hosting server.



    [1]: https://swagger.io
  affected_package: io.swagger:swagger-parser
  vulnerable_versions:
  - "< 1.0.31"
  severity: high
  package_manager: maven
  cve:
  - CVE-2017-1000207
  cwe:
  - CWE-94
  disclosed_date: 2017-07-13
  created_date: 2017-11-28
  last_modified_date: 2017-11-28
  credit:
  - Unknown
  references:
  - https://github.com/swagger-api/swagger-parser/pull/481
  - https://nvd.nist.gov/vuln/detail/CVE-2017-1000207
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOSWAGGER-31589
