---
- id: ossindex:maven:io.swagger:swagger-codegen:8405007859
  title: Remote Code Execution
  description: "> Maliciously crafted Swagger documents can be used to dynamically
    create HTTP API clients and servers with embedded arbitrary code execution in
    the underlying operating system. This is achieved by the fact that some parsers/generators
    trust insufficiently sanitized parameters within a Swagger document to generate
    a client code base.\n> \n> -- [rapid7.com](https://community.rapid7.com/community/infosec/blog/2016/06/23/r7-2016-06-remote-code-execution-via-swagger-parameter-injection-cve-2016-5641)"
  affected_package: io.swagger:swagger-codegen
  vulnerable_versions:
  - "<2.2.0"
  package_manager: maven
  disclosed_date: 2017-08-01
  created_date: 2017-08-01
  last_modified_date: 2017-08-01
  credit:
  - OSSIndex
  references:
  - https://community.rapid7.com/community/infosec/blog/2016/06/23/r7-2016-06-remote-code-execution-via-swagger-parameter-injection-cve-2016-5641
  - https://github.com/swagger-api/swagger-codegen/commit/80666394f671ec38f363732a16ed0fb284fd295c
  - https://github.com/swagger-api/swagger-codegen/pull/3201
  source_url: https://ossindex.net/resource/package/7108612439/vulnerabilities
- id: snykio:maven:io.swagger:swagger-codegen:30444
  title: Arbitrary Code Execution
  description: |
    [`io.swagger:swagger-codegen`][1] is a simple yet powerful
    representation of your RESTful API.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution via parameter injection. By leveraging this vulnerability, an
    attacker can inject arbitrary execution code embedded with a client or
    server generated automatically to interact with the definition of
    service.



    [1]: https://swagger.io
  affected_package: io.swagger:swagger-codegen
  vulnerable_versions:
  - "< 2.2.0"
  severity: high
  package_manager: maven
  cve:
  - CVE-2016-5641
  cwe:
  - CWE-94
  disclosed_date: 2016-07-21
  created_date: 2016-07-21
  last_modified_date: 2016-07-21
  credit:
  - Scott Davis
  references:
  - https://community.rapid7.com/community/infosec/blog/2016/06/23/r7-2016-06-remote-code-execution-via-swagger-parameter-injection-cve-2016-5641
  - https://github.com/swagger-api/swagger-codegen/pull/3201
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOSWAGGER-30444
- id: snykio:maven:io.swagger:swagger-codegen:31588
  title: Arbitrary Code Execution
  description: |
    [`io.swagger:swagger-codegen`][1] is a simple yet powerful
    representation of your RESTful API.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution via the yaml parsing functionality. When a maliciously crafted
    yaml Open-API specification is parsed, it is possible to execute
    arbitrary code on the hosting server. This in particular, affects the
    \'generate\' and \'validate\' command in swagger-codegen (&lt;= 2.2.2)
    and can lead to arbitrary code being executed when these commands are
    used on a well-crafted yaml specification.



    [1]: https://swagger.io
  affected_package: io.swagger:swagger-codegen
  vulnerable_versions:
  - "< 2.2.3"
  severity: high
  package_manager: maven
  cve:
  - CVE-2017-1000207
  cwe:
  - CWE-94
  disclosed_date: 2017-07-13
  created_date: 2017-11-28
  last_modified_date: 2017-11-28
  credit:
  - Unknown
  references:
  - https://github.com/swagger-api/swagger-parser/pull/481
  - https://nvd.nist.gov/vuln/detail/CVE-2017-1000207
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOSWAGGER-31588
