---
- id: ossindex:maven:org.apache.struts:struts2-config-browser-plugin:2013-11-02
  title: '[CVE-2013-6348]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: Multiple cross-site scripting (XSS) vulnerabilities in Apache Struts
    2.3.15.3 allow remote attackers to inject arbitrary web script or HTML via the
    namespace parameter to (1) actionNames.action and (2) showConfig.action in config-browser/.
  affected_package: org.apache.struts:struts2-config-browser-plugin
  vulnerable_versions:
  - ">=2.0.0 <=2.3.15.3"
  package_manager: maven
  cve:
  - CVE-2013-6348
  credit:
  - OSSIndex
  references:
  - http://en.wooyun.org/bugs/wooyun-2013-034?2592
  - http://osvdb.org/99047
  - http://osvdb.org/99048
  - http://packetstormsecurity.com/files/123805/Struts-2.3.15.3-Cross-Site-Scripting.html
  - http://seclists.org/fulldisclosure/2013/Oct/244
  - http://www.securitytracker.com/id/1029266
  source_url: https://ossindex.net/resource/package/7015343709/vulnerabilities
- id: snykio:maven:org.apache.struts:struts2-config-browser-plugin:2013-10-28
  title: Cross-site Scripting (XSS)
  description: |
    [`org.apache.struts:struts2-config-browser-plugin`][1] Multiple
    cross-site scripting (XSS) vulnerabilities in Apache Struts 2.3.15.3
    allow remote attackers to inject arbitrary web script or HTML via the
    namespace parameter to (1) actionNames.action and (2) showConfig.action
    in config-browser/.



    [1]: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22struts2-config-browser-plugin%22
    \n[`org.apache.struts:struts2-config-browser-plugin`][1] Multiple
    cross-site scripting (XSS) vulnerabilities in Apache Struts 2.3.15.3
    allow remote attackers to inject arbitrary web script or HTML via the
    namespace parameter to (1) actionNames.action and (2) showConfig.action
    in config-browser/.



    [1]: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22struts2-config-browser-plugin%22
    \n<XSS markdown="1"> ## References   {#references}

     * [Redhat Bugzilla][1]
    * [Jira Issue][2]

     </XSS>



    [1]: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-6348
    [2]: https://issues.apache.org/jira/browse/WW-4213
    \n<XSS markdown="1"> ## References   {#references}

     * [Redhat Bugzilla][1]
    * [Jira Issue][2]

     </XSS>



    [1]: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-6348
    [2]: https://issues.apache.org/jira/browse/WW-4213
  affected_package: org.apache.struts:struts2-config-browser-plugin
  vulnerable_versions:
  - ">= 2 <= 2.3.15.3"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2013-6348
  cwe:
  - CWE-79
  credit:
  - Unknown
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHESTRUTS-30037
- id: victims:maven:org.apache.struts:struts2-config-browser-plugin:date
  title: 'Apache Struts2: XSS via malicious action parameter'
  description: "Multiple cross-site scripting (XSS) vulnerabilities in Apache Struts2
    allow  remote attackers to inject arbitrary web script or HTML via the namespace
    \ parameter to actionNames.action and showConfig.action in config-browser/. \n"
  affected_package: org.apache.struts:struts2-config-browser-plugin
  vulnerable_versions:
  - "<=2.3.15.3"
  - '2'
  severity: high
  package_manager: maven
  cve:
  - 2013-6348
  credit:
  - Victims CVE Database
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-6348
  - https://issues.apache.org/jira/browse/WW-4213
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/java/2013/6348.yaml
