---
- id: snykio:maven:org.jenkins-ci.plugins:azure-publishersettings-credentials:174461
  title: Security Issue
  description: |
    [org.jenkins-ci.plugins:azure-publishersettings-credentials][1] is a
    Manage Azure PublisherSettings using Jenkins Credentials API.

    Affected versions of this package have Security Issue. The plugin stores
    credentials unencrypted in the credentials.xml file on the Jenkins
    master where they could be viewed by users with access to the master
    file system.



    [1]: https://github.com/jenkinsci/azure-publishersettings-credentials-plugin/blob/master/pom.xml
  affected_package: org.jenkins-ci.plugins:azure-publishersettings-credentials
  vulnerable_versions:
  - "< 1.5"
  severity: low
  package_manager: maven
  cve:
  - CVE-2019-10303
  cwe:
  - CWE-255
  disclosed_date: 2019-04-18
  created_date: 2019-04-18
  last_modified_date: 2019-04-18
  credit:
  - Viktor Gazdag
  references:
  - https://jenkins.io/security/advisory/2019-04-17/#SECURITY-844
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-174461
