---
- id: ossindex:maven:org.springframework.security:spring-security-config:2017-05-25
  title: "[CVE-2016-5007]  Permissions, Privileges, and Access Controls"
  description: Both Spring Security 3.2.x, 4.0.x, 4.1.0 and the Spring Framework 3.2.x,
    4.0.x, 4.1.x, 4.2.x rely on URL pattern mappings for authorization and for mapping
    requests to controllers respectively. Differences in the strictness of the pattern
    matching mechanisms, for example with regards to space trimming in path segments,
    can lead Spring Security to not recognize certain paths as not protected that
    are in fact mapped to Spring MVC controllers that should be protected. The problem
    is compounded by the fact that the Spring Framework provides richer features with
    regards to pattern matching as well as by the fact that pattern matching in each
    Spring Security and the Spring Framework can easily be customized creating additional
    differences.
  affected_package: org.springframework.security:spring-security-config
  vulnerable_versions:
  - ">=3.2.0 <4.1.1"
  package_manager: maven
  cve:
  - CVE-2016-5007
  credit:
  - OSSIndex
  references:
  - http://www.securityfocus.com/bid/91687
  - https://pivotal.io/security/cve-2016-5007
  source_url: https://ossindex.net/resource/package/7015205379/vulnerabilities
- id: snykio:maven:org.springframework.security:spring-security-config:2016-07-11
  title: Authentication Bypass
  description: |
    [`org.springframework.security:spring-security-config`][1] Affected
    versions of this package are vulnerable to Authentication Bypass. The
    strictness of the Spring Security, and the Spring Framework request
    mapping may differ, which could lead to resources not being secured.



    [1]: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-security-config%22
    \n[`org.springframework.security:spring-security-config`][1] Affected
    versions of this package are vulnerable to Authentication Bypass. The
    strictness of the Spring Security, and the Spring Framework request
    mapping may differ, which could lead to resources not being secured.



    [1]: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-security-config%22
  affected_package: org.springframework.security:spring-security-config
  vulnerable_versions:
  - ">= 3.2.0.RELEASE < 4.1.1.RELEASE"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2016-5007
  cwe:
  - CWE-41
  credit:
  - Clément Notin
  references:
  - https://pivotal.io/security/cve-2016-5007
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKSECURITY-31336
