---
- id: snykio:maven:org.jenkins-ci.plugins:application-director-plugin:469194
  title: Insufficiently Protected Credentials
  description: |
    [org.jenkins-ci.plugins:application-director-plugin][1] is a plugin that
    integrates Jenkins to vFabric Application Director.

    Affected versions of this package are vulnerable to Insufficiently
    Protected Credentials. The plugin stores credentials unencrypted in its
    global configuration file on the Jenkins master where they can be viewed
    by users with access to the master file system.



    [1]: https://plugins.jenkins.io/application-director-plugin
  affected_package: org.jenkins-ci.plugins:application-director-plugin
  vulnerable_versions:
  - ">= 0"
  severity: low
  package_manager: maven
  cve:
  - CVE-2019-10419
  cwe:
  - CWE-312
  disclosed_date: 2019-09-25
  created_date: 2019-09-26
  last_modified_date: 2019-09-26
  credit:
  - IB Boost
  - James Holderness
  references:
  - https://jenkins.io/security/advisory/2019-09-25/
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-469194
