---
- id: snykio:maven:org.jenkins-ci.plugins:aqua-serverless:466732
  title: Insufficiently Protected Credentials
  description: |
    [org.jenkins-ci.plugins:aqua-serverless][1] is a Jenkins plugin for
    serverless security scanning by Aqua Security

    Affected versions of this package are vulnerable to Insufficiently
    Protected Credentials. It transmitted configured passwords in plain text
    as part of job configuration forms, potentially resulting in their
    exposure.



    [1]: https://plugins.jenkins.io/aqua-serverless
  affected_package: org.jenkins-ci.plugins:aqua-serverless
  vulnerable_versions:
  - "< 1.0.5"
  severity: low
  package_manager: maven
  cve:
  - CVE-2019-10397
  cwe:
  - CWE-522
  disclosed_date: 2019-09-12
  created_date: 2019-09-13
  last_modified_date: 2019-09-13
  credit:
  - IB Boost
  - James Holderness
  references:
  - https://github.com/jenkinsci/aqua-serverless-plugin/commit/0e437736c0cfff7a68928b92dd655a61ba0adbdc
  - https://jenkins.io/security/advisory/2019-09-12/
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-466732
