---
- id: snykio:maven:org.apache.karaf.config:org.apache.karaf.config.core:174625
  title: Directory Traversal
  description: |
    [org.apache.karaf.config:org.apache.karaf.config.core][1] is a bundle
    that provides Karaf services.

    Affected versions of this package are vulnerable to Directory Traversal.
    The Apache Karaf Config component provides an install method that can be
    used to traverse in any directory and overwrite existing files within an
    application. The condition of this vulnerability being exploited is
    considered low if the permissions of Karaf process has limited
    permission on the file system.



    [1]: https://karaf.apache.org
  affected_package: org.apache.karaf.config:org.apache.karaf.config.core
  vulnerable_versions:
  - "< 4.2.5"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2019-0226
  cwe:
  - CWE-22
  disclosed_date: 2019-05-06
  created_date: 2019-05-09
  last_modified_date: 2019-05-09
  credit:
  - Ma Lingtao
  references:
  - https://github.com/apache/karaf/commit/fe3bc4108e5a8b3c804e5da91ec0d5695588eb25
  - https://github.com/apache/karaf/pull/805
  - https://lists.apache.org/thread.html/1baa6f1df0e95fb1cd679067117354af2ab4423277d9a0ff6e8bf790@%3Cdev.karaf.apache.org%3E
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEKARAFCONFIG-174625
