---
- id: snykio:maven:org.jenkins-ci.plugins:script-security:2016-03-28
  title: Arbitrary Code Execution
  description: |
    [org.jenkins-ci.plugins:script-security][1] Allows Jenkins
    administrators to control what in-process scripts can be run by
    less-privileged users.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution. It might allow remote attackers to bypass a Groovy sandbox
    protection mechanism via a plugin that performs (1) direct field access
    or (2) get/set array operations.



    [1]: https://github.com/jenkinsci/script-security-plugin
    \n[org.jenkins-ci.plugins:script-security][1] Allows Jenkins
    administrators to control what in-process scripts can be run by
    less-privileged users.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution. It might allow remote attackers to bypass a Groovy sandbox
    protection mechanism via a plugin that performs (1) direct field access
    or (2) get/set array operations.



    [1]: https://github.com/jenkinsci/script-security-plugin
    \n[org.jenkins-ci.plugins:script-security][1] Allows Jenkins
    administrators to control what in-process scripts can be run by
    less-privileged users.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution. It might allow remote attackers to bypass a Groovy sandbox
    protection mechanism via a plugin that performs (1) direct field access
    or (2) get/set array operations.



    [1]: https://github.com/jenkinsci/script-security-plugin
  affected_package: org.jenkins-ci.plugins:script-security
  vulnerable_versions:
  - "< 1.18.1"
  severity: high
  package_manager: maven
  cve:
  - CVE-2016-3102
  cwe:
  - CWE-254
  credit:
  - Daniel Beck
  references:
  - https://jenkins.io/security/advisory/2016-04-11/
  - https://github.com/jenkinsci/script-security-plugin/commit/e7d3bc9c1e25caa23cea33381134a4baaedc75b8
  - https://nvd.nist.gov/vuln/detail/CVE-2016-3102
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-32254
- id: snykio:maven:org.jenkins-ci.plugins:script-security:2017-12-01
  title: Arbitrary File Read
  description: |
    [org.jenkins-ci.plugins:script-security][1] allows Jenkins
    administrators to control what in-process scripts can be run by
    less-privileged users.

    Affected versions of this package are vulnerable to Arbitrary File Read.
    Users with the ability to configure sandboxed Groovy scripts are able to
    use a type coercion feature in Groovy to create new `File` objects from
    strings. This allowed reading arbitrary files on the Jenkins master file
    system. Such a type coercion is now subject to sandbox protection and
    considered to be a call to the `new File(String)` constructor for the
    purpose of in-process script approval.



    [1]: https://github.com/jenkinsci/script-security-plugin
    \n[org.jenkins-ci.plugins:script-security][1] allows Jenkins
    administrators to control what in-process scripts can be run by
    less-privileged users.

    Affected versions of this package are vulnerable to Arbitrary File Read.
    Users with the ability to configure sandboxed Groovy scripts are able to
    use a type coercion feature in Groovy to create new `File` objects from
    strings. This allowed reading arbitrary files on the Jenkins master file
    system. Such a type coercion is now subject to sandbox protection and
    considered to be a call to the `new File(String)` constructor for the
    purpose of in-process script approval.



    [1]: https://github.com/jenkinsci/script-security-plugin
    \n[org.jenkins-ci.plugins:script-security][1] allows Jenkins
    administrators to control what in-process scripts can be run by
    less-privileged users.

    Affected versions of this package are vulnerable to Arbitrary File Read.
    Users with the ability to configure sandboxed Groovy scripts are able to
    use a type coercion feature in Groovy to create new `File` objects from
    strings. This allowed reading arbitrary files on the Jenkins master file
    system. Such a type coercion is now subject to sandbox protection and
    considered to be a call to the `new File(String)` constructor for the
    purpose of in-process script approval.



    [1]: https://github.com/jenkinsci/script-security-plugin
  affected_package: org.jenkins-ci.plugins:script-security
  vulnerable_versions:
  - "< 1.37"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2017-1000505
  cwe:
  - CWE-200
  credit:
  - Gregory Draperi
  references:
  - https://jenkins.io/security/advisory/2017-12-11/
  - https://github.com/jenkinsci/script-security-plugin/commit/4caaa50e570dafa15c73badac250eb31878ab3ba
  - https://nvd.nist.gov/vuln/detail/CVE-2017-1000505
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-32171
