---
- id: snykio:maven:org.jenkins-ci.plugins:config-file-provider:32226
  title: Arbitrary File Read
  description: |
    [org.jenkins-ci.plugins:config-file-provider][1] allows to administrate
    different file types right in the Jenkins UI. e.g. the maven settings
    (settings.xml) or simple text files These files can be used/referenced
    in jobs during execution.

    Affected versions of this package are vulnerable to Arbitrary File Read.
    Users with only Overall/Read access to Jenkins were able to access URLs
    directly that allowed viewing these files. Access to view these files
    now requires sufficient permissions to configure the provided files,
    view the configuration of the folder in which the configuration files
    are defined, or have Job/Configure permissions to a job able to use
    these files.



    [1]: https://github.com/jenkinsci/config-file-provider-plugin
  affected_package: org.jenkins-ci.plugins:config-file-provider
  vulnerable_versions:
  - "< 2.16.2"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2017-1000104
  cwe:
  - CWE-264
  disclosed_date: 2017-08-07
  created_date: 2018-04-25
  last_modified_date: 2018-04-25
  credit:
  - Thanh Ha
  references:
  - https://jenkins.io/security/advisory/2017-08-07/
  - https://nvd.nist.gov/vuln/detail/CVE-2017-1000104
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-32226
