---
- id: ossindex:maven:org.apache.struts:struts2-config-browser-plugin:358973
  title: '[CVE-2013-6348]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: Multiple cross-site scripting (XSS) vulnerabilities in Apache Struts
    2.3.15.3 allow remote attackers to inject arbitrary web script or HTML via the
    namespace parameter to (1) actionNames.action and (2) showConfig.action in config-browser/.
  affected_package: org.apache.struts:struts2-config-browser-plugin
  vulnerable_versions:
  - ">=2.0.0 <=2.3.15.3"
  package_manager: maven
  cve:
  - CVE-2013-6348
  disclosed_date: 2013-11-02
  created_date: 2013-11-02
  last_modified_date: 2017-06-02
  credit:
  - OSSIndex
  references:
  - http://en.wooyun.org/bugs/wooyun-2013-034?2592
  - http://osvdb.org/99047
  - http://osvdb.org/99048
  - http://packetstormsecurity.com/files/123805/Struts-2.3.15.3-Cross-Site-Scripting.html
  - http://seclists.org/fulldisclosure/2013/Oct/244
  - http://www.securitytracker.com/id/1029266
  source_url: https://ossindex.net/resource/package/7015343709/vulnerabilities
- id: snykio:maven:org.apache.struts:struts2-config-browser-plugin:30037
  title: Cross-site Scripting (XSS)
  description: |+
    [org.apache.struts:struts2-config-browser-plugin][1] is a free,
    open-source, MVC framework for creating Java web applications.

    Affected versions of this package are vulnerable to multiple Cross-site
    Scripting (XSS) vulnerabilities, allowing remote attackers to inject
    arbitrary web script or HTML via the namespace parameter to (1)
    actionNames.action and (2) showConfig.action in config-browser.



    [1]: https://struts.apache.org
    \nA cross-site scripting attack occurs when the attacker tricks a
    legitimate web-based application or site to accept a request as
    originating from a trusted source.

    This is done by escaping the context of the web application; the web
    application then delivers that data to its users along with other
    trusted dynamic content, without validating it. The browser unknowingly
    executes malicious script on the client side (through client-side
    languages; usually JavaScript or HTML) in order to perform actions that
    are otherwise typically blocked by the browser’s Same Origin Policy.

    ֿInjecting malicious code is the most prevalent manner by which XSS is
    exploited; for this reason, escaping characters in order to prevent this
    manipulation is the top method for securing code against this
    vulnerability.

    Escaping means that the application is coded to mark key characters, and
    particularly key characters included in user input, to prevent those
    characters from being interpreted in a dangerous context. For example,
    in HTML, `<` can be coded as `&lt`; and `>` can be coded as `&gt`; in
    order to be interpreted and displayed as themselves in text, while
    within the code itself, they are used for HTML tags. If malicious
    content is injected into an application that escapes special characters
    and that malicious content uses `<` and `>` as HTML tags, those
    characters are nonetheless not interpreted as HTML tags by the browser
    if they’ve been correctly escaped in the application code and in this
    way the attempted attack is diverted.

    The most prominent use of XSS is to steal cookies (source: OWASP
    HttpOnly) and hijack user sessions, but XSS exploits have been used to
    expose sensitive information, enable access to privileged services and
    functionality and deliver malware.

    ### Types of attacks   {#types-of-attacks}

    There are a few methods by which XSS can be manipulated:

    | Type | Origin | Description |
    |----------
    | **Stored** | Server | The malicious code is inserted in the application (usually as a link) by the attacker. The code is activated every time a user clicks the link. |
    | **Reflected** | Server | The attacker delivers a malicious link externally from the vulnerable web site application to a user. When clicked, malicious code is sent to the vulnerable web site, which reflects the attack back to the user’s browser. |
    | **DOM-based** | Client | The attacker forces the user’s browser to render a malicious page. The data in the page itself delivers the cross-site scripting data. |
    | **Mutated** |  | The attacker injects code that appears safe, but is then rewritten and modified by the browser, while parsing the markup. An example is rebalancing unclosed quotation marks or even adding quotation marks to unquoted parameters. |

    ### Affected environments   {#affected-environments}

    The following environments are susceptible to an XSS attack:

    * Web servers
    * Application servers
    * Web application environments

    ### How to prevent   {#how-to-prevent}

    This section describes the top best practices designed to specifically
    protect your code:

    * Sanitize data input in an HTTP request before reflecting it back,
      ensuring all data is validated, filtered or escaped before echoing
      anything back to the user, such as the values of query parameters
      during searches.
    * Convert special characters such as `?`, `&`, `/`, `<`, `>` and spaces
      to their respective HTML or URL encoded equivalents.
    * Give users the option to disable client-side scripts.
    * Redirect invalid requests.
    * Detect simultaneous logins, including those from two separate IP
      addresses, and invalidate those sessions.
    * Use and enforce a Content Security Policy (source: Wikipedia) to
      disable any features that might be manipulated for an XSS attack.
    * Read the documentation for any of the libraries referenced in your
      code to understand which elements allow for embedded HTML.

  affected_package: org.apache.struts:struts2-config-browser-plugin
  vulnerable_versions:
  - ">= 2.0.5 < 2.3.16"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2013-6348
  cwe:
  - CWE-79
  disclosed_date: 2013-10-28
  created_date: 2013-10-28
  last_modified_date: 2013-10-28
  credit:
  - Unknown
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-6348
  - https://github.com/apache/struts/commit/01584fabc74635d63a1b2670f18d8fcd1ee046cc
  - https://github.com/apache/struts/commit/fd27e5cc748420a53d51e0e19a10efe8c582c2c0
  - https://issues.apache.org/jira/browse/WW-4213
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHESTRUTS-30037
- id: victims:maven:org.apache.struts:struts2-config-browser-plugin:2013-6348
  title: 'Apache Struts2: XSS via malicious action parameter'
  description: "Multiple cross-site scripting (XSS) vulnerabilities in Apache Struts2
    allow  remote attackers to inject arbitrary web script or HTML via the namespace
    \ parameter to actionNames.action and showConfig.action in config-browser/. \n"
  affected_package: org.apache.struts:struts2-config-browser-plugin
  vulnerable_versions:
  - '2'
  - "<=2.3.15.3"
  severity: high
  package_manager: maven
  cve:
  - CVE-2013-6348
  credit:
  - Victims CVE Database
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-6348
  - https://issues.apache.org/jira/browse/WW-4213
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/java/2013/6348.yaml
