---
- id: ossindex:maven:org.apache.portals.jetspeed-2:jetspeed-security:8398915909
  title: "[CVE-2016-0710]  Improper Neutralization of Special Elements used in an
    SQL Command (SQL Injection)"
  description: Multiple SQL injection vulnerabilities in the User Manager service
    in Apache Jetspeed before 2.3.1 allow remote attackers to execute arbitrary SQL
    commands via the (1) role or (2) user parameter to services/usermanager/users/.
  affected_package: org.apache.portals.jetspeed-2:jetspeed-security
  vulnerable_versions:
  - "<2.3.1"
  package_manager: maven
  cve:
  - CVE-2016-0710
  disclosed_date: 2016-04-11
  created_date: 2016-04-11
  last_modified_date: 2017-06-02
  credit:
  - OSSIndex
  references:
  - http://haxx.ml/post/140552592371/remote-code-execution-in-apache-jetspeed-230-and
  - http://packetstormsecurity.com/files/136489/Apache-Jetspeed-Arbitrary-File-Upload.html
  - http://www.rapid7.com/db/modules/exploit/multi/http/apache_jetspeed_file_upload
  - https://mail-archives.apache.org/mod_mbox/portals-jetspeed-user/201603.mbox/%3C046318A1-226E-453F-9394-B84F1A33E6A4@bluesunrise.com%3E
  - https://portals.apache.org/jetspeed-2/security-reports.html#CVE-2016-0710
  - https://www.exploit-db.com/exploits/39643/
  source_url: https://ossindex.net/resource/package/7015349113/vulnerabilities
- id: ossindex:maven:org.apache.portals.jetspeed-2:jetspeed-security:8398917177
  title: "[CVE-2016-2171]  Permissions, Privileges, and Access Controls"
  description: The User Manager service in Apache Jetspeed before 2.3.1 does not properly
    restrict access using Jetspeed Security, which allows remote attackers to (1)
    add, (2) edit, or (3) delete users via the REST API.
  affected_package: org.apache.portals.jetspeed-2:jetspeed-security
  vulnerable_versions:
  - "<2.3.1"
  package_manager: maven
  cve:
  - CVE-2016-2171
  disclosed_date: 2016-04-11
  created_date: 2016-04-11
  last_modified_date: 2017-06-02
  credit:
  - OSSIndex
  references:
  - http://haxx.ml/post/140552592371/remote-code-execution-in-apache-jetspeed-230-and
  - http://mail-archives.apache.org/mod_mbox/portals-jetspeed-user/201603.mbox/%3CB9165E38-F3D8-496D-8642-8A53FCAC736A%40gmail.com%3E
  - https://portals.apache.org/jetspeed-2/security-reports.html#CVE-2016-2171
  source_url: https://ossindex.net/resource/package/7015349113/vulnerabilities
- id: snykio:maven:org.apache.portals.jetspeed-2:jetspeed-security:30705
  title: SQL Injection
  description: |
    [`org.apache.portals.jetspeed-2:jetspeed-security`][1] Multiple SQL
    injection vulnerabilities in the User Manager service in Apache Jetspeed
    before 2.3.1 allow remote attackers to execute arbitrary SQL commands
    via the (1) role or (2) user parameter to services/usermanager/users/.



    [1]: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jetspeed-security%22
  affected_package: org.apache.portals.jetspeed-2:jetspeed-security
  vulnerable_versions:
  - "< 2.3.1"
  severity: high
  package_manager: maven
  cve:
  - CVE-2016-0710
  cwe:
  - CWE-89
  disclosed_date: 2016-03-09
  created_date: 2016-03-09
  last_modified_date: 2016-03-09
  credit:
  - Unknown
  references:
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-0710
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEPORTALSJETSPEED2-30705
- id: snykio:maven:org.apache.portals.jetspeed-2:jetspeed-security:30706
  title: Arbitrary User Modification
  description: |
    [`org.apache.portals.jetspeed-2:jetspeed-security`][1] The User Manager
    service in Apache Jetspeed before 2.3.1 does not properly restrict
    access using Jetspeed Security, which allows remote attackers to (1)
    add, (2) edit, or (3) delete users via the REST API.



    [1]: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jetspeed-security%22
  affected_package: org.apache.portals.jetspeed-2:jetspeed-security
  vulnerable_versions:
  - "< 2.3.1"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2016-2171
  cwe:
  - CWE-264
  disclosed_date: 2016-04-08
  created_date: 2016-04-08
  last_modified_date: 2016-04-08
  credit:
  - Unknown
  references:
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-2171
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEPORTALSJETSPEED2-30706
