---
- id: snykio:maven:org.apache.cxf:cxf-rt-security:2014-10-25
  title: Improper Authentication
  description: |
    [`org.apache.cxf:cxf-rt-security`][1] is an open source services
    framework.

    Apache WSS4J before 1.6.17 and 2.x before 2.0.2, as used in Apache CXF
    2.7.x before 2.7.13 and 3.0.x before 3.0.2, when using TransportBinding,
    does not properly enforce the SAML SubjectConfirmation method security
    semantics, which allows remote attackers to conduct spoofing attacks via
    unspecified vectors.



    [1]: https://http://cxf.apache.org/
    \n[`org.apache.cxf:cxf-rt-security`][1] is an open source services
    framework.

    Apache WSS4J before 1.6.17 and 2.x before 2.0.2, as used in Apache CXF
    2.7.x before 2.7.13 and 3.0.x before 3.0.2, when using TransportBinding,
    does not properly enforce the SAML SubjectConfirmation method security
    semantics, which allows remote attackers to conduct spoofing attacks via
    unspecified vectors.



    [1]: https://http://cxf.apache.org/
    \n[`org.apache.cxf:cxf-rt-security`][1] is an open source services
    framework.

    Apache WSS4J before 1.6.17 and 2.x before 2.0.2, as used in Apache CXF
    2.7.x before 2.7.13 and 3.0.x before 3.0.2, when using TransportBinding,
    does not properly enforce the SAML SubjectConfirmation method security
    semantics, which allows remote attackers to conduct spoofing attacks via
    unspecified vectors.



    [1]: https://http://cxf.apache.org/
  affected_package: org.apache.cxf:cxf-rt-security
  vulnerable_versions:
  - ">= 2 <= 2.7.12"
  - ">= 3 <= 3.0.1"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2014-3623
  cwe:
  - CWE-287
  credit:
  - Unknown
  references:
  - http://cxf.apache.org/security-advisories.data/CVE-2014-3623.txt.asc
  - https://bugzilla.redhat.com/CVE-2014-3623
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECXF-30015
- id: victims:maven:org.apache.cxf:cxf-rt-security:date
  title: Improper security semantics enforcement of SAML SubjectConfirmation methods
  affected_package: org.apache.cxf:cxf-rt-security
  vulnerable_versions:
  - "<=2.7.12"
  - '2'
  - "<=3.0.1"
  - '3'
  patched_versions:
  - ">=2.7.13"
  - '2'
  - ">=3.0.2"
  - '3'
  severity: high
  package_manager: maven
  cve:
  - 2014-3623
  credit:
  - Victims CVE Database
  references:
  - http://cxf.apache.org/security-advisories.data/CVE-2014-3623.txt.asc
  - https://bugzilla.redhat.com/CVE-2014-3623
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/java/2014/3623.yaml
