---
- id: ossindex:maven:org.apache.geronimo.configs:derby:2005-12-31
  title: "[CVE-2005-4849]  Information Exposure"
  description: Apache Derby before 10.1.2.1 exposes the (1) user and (2) password
    attributes in cleartext via (a) the RDBNAM parameter of the ACCSEC command and
    (b) the output of the DatabaseMetaData.getURL function, which allows context-dependent
    attackers to obtain sensitive information.
  affected_package: org.apache.geronimo.configs:derby
  vulnerable_versions:
  - 10.1.1.0
  package_manager: maven
  cve:
  - CVE-2005-4849
  credit:
  - OSSIndex
  references:
  - http://db.apache.org/derby/releases/release-10.1.2.1.html
  - http://issues.apache.org/jira/browse/DERBY-530
  - http://issues.apache.org/jira/browse/DERBY-559
  source_url: https://ossindex.net/resource/package/7015371061/vulnerabilities
- id: ossindex:maven:org.apache.geronimo.configs:derby:2007-07-05
  title: "[CVE-2006-7217] Apache Derby before 10.2.1.6 does not determine schema privilege
    requirements du..."
  description: Apache Derby before 10.2.1.6 does not determine schema privilege requirements
    during the DropSchemaNode bind phase, which allows remote authenticated users
    to execute arbitrary drop schema statements in SQL authorization mode.
  affected_package: org.apache.geronimo.configs:derby
  vulnerable_versions:
  - 10.1.1.0
  - 10.1.2.1
  - 10.1.3.1
  package_manager: maven
  cve:
  - CVE-2006-7217
  credit:
  - OSSIndex
  references:
  - http://db.apache.org/derby/releases/release-10.2.1.6.html
  - http://issues.apache.org/jira/browse/DERBY-1858
  - http://secunia.com/advisories/28636
  - http://www.novell.com/linux/security/advisories/suse_security_summary_report.html
  source_url: https://ossindex.net/resource/package/7015371061/vulnerabilities
- id: ossindex:maven:org.apache.geronimo.configs:derby:2007-07-05
  title: "[CVE-2006-7216] Apache Derby before 10.2.1.6 does not determine privilege
    requirements for lock ..."
  description: Apache Derby before 10.2.1.6 does not determine privilege requirements
    for lock table statements at compilation time, and consequently does not enforce
    privilege requirements at execution time, which allows remote authenticated users
    to lock arbitrary tables.
  affected_package: org.apache.geronimo.configs:derby
  vulnerable_versions:
  - 10.1.1.0
  - 10.1.2.1
  - 10.1.3.1
  package_manager: maven
  cve:
  - CVE-2006-7216
  credit:
  - OSSIndex
  references:
  - http://db.apache.org/derby/releases/release-10.2.1.6.html
  - http://issues.apache.org/jira/browse/DERBY-1708
  source_url: https://ossindex.net/resource/package/7015371061/vulnerabilities
- id: ossindex:maven:org.apache.geronimo.configs:derby:2010-08-16
  title: "[CVE-2009-4269]  Cryptographic Issues"
  description: The password hash generation algorithm in the BUILTIN authentication
    functionality for Apache Derby before 10.6.1.0 performs a transformation that
    reduces the size of the set of inputs to SHA-1, which produces a small search
    space that makes it easier for local and possibly remote attackers to crack passwords
    by generating hash collisions, related to password substitution.
  affected_package: org.apache.geronimo.configs:derby
  vulnerable_versions:
  - 10.5.3.0
  package_manager: maven
  cve:
  - CVE-2009-4269
  credit:
  - OSSIndex
  references:
  - http://blogs.sun.com/kah/entry/derby_10_6_1_has
  - http://db.apache.org/derby/releases/release-10.6.1.0.cgi#Fix+for+Security+Bug+CVE-2009-4269
  - http://db.apache.org/derby/releases/release-10.6.1.0.cgi%23Fix%20for%20Security%20Bug%20CVE-2009-4269
  - http://marc.info/?l=apache-db-general&m=127428514905504&w=1
  - http://marcellmajor.com/derbyhash.html
  - http://secunia.com/advisories/42948
  - http://secunia.com/advisories/42970
  - http://www.oracle.com/technetwork/topics/security/cpujan2011-194091.html
  - http://www.securityfocus.com/bid/42637
  - http://www.securitytracker.com/id?1024977
  - http://www.vupen.com/english/advisories/2011/0149
  - https://issues.apache.org/jira/browse/DERBY-4483
  source_url: https://ossindex.net/resource/package/7015371061/vulnerabilities
- id: ossindex:maven:org.apache.geronimo.configs:derby:2016-10-03
  title: '[CVE-2015-1832]  Resource Management Errors, Improper Restriction of XML
    External Entity Reference ("XXE")'
  description: XML external entity (XXE) vulnerability in the SqlXmlUtil code in Apache
    Derby before 10.12.1.1, when a Java Security Manager is not in place, allows context-dependent
    attackers to read arbitrary files or cause a denial of service (resource consumption)
    via vectors involving XmlVTI and the XML datatype.
  affected_package: org.apache.geronimo.configs:derby
  vulnerable_versions:
  - "<10.12.1.1"
  package_manager: maven
  cve:
  - CVE-2015-1832
  credit:
  - OSSIndex
  references:
  - http://www-01.ibm.com/support/docview.wss?uid=swg21990100
  - http://www.securityfocus.com/bid/93132
  - https://issues.apache.org/jira/browse/DERBY-6807
  - https://svn.apache.org/viewvc?view=revision&revision=1691461
  source_url: https://ossindex.net/resource/package/7015371061/vulnerabilities
