---
- id: friendsofphp:packagist:illuminate/database:2014-05-20
  title: Risk of mass-assignment vulnerabilities
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4.0.0 <4.0.99"
  - ">=4.1.0 <4.1.29"
  package_manager: packagist
  credit:
  - FriendsOfPHP
  references:
  - https://laravel.com/docs/5.1/upgrade#upgrade-4.1.29
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/amphp/artax/CVE-2016-5385.yaml/blob/master/amphp/artax/2017-05-09.yaml/blob/master/amphp/http/2018-03-15.yaml/blob/master/phpxmlrpc/extras/2017-10-29.yaml/blob/master/zfr/zfr-oauth2-server-module/2014-04-26.yaml/blob/master/kazist/phpwhois/CVE-2015-5243.yaml/blob/master/phpwhois/phpwhois/CVE-2015-5243.yaml/blob/master/phpunit/phpunit/CVE-2017-9841.yaml/blob/master/bugsnag/bugsnag-laravel/CVE-2016-5385.yaml/blob/master/paypal/merchant-sdk-php/CVE-2017-6099.yaml/blob/master/paragonie/random_compat/2016-03-16.yaml/blob/master/codeigniter/framework/2016-07-26-1.yaml/blob/master/codeigniter/framework/2015-10-31-1.yaml/blob/master/pagarme/pagarme-php/2017-11-20.yaml/blob/master/sylius/sylius/2018-07-09.yaml/blob/master/sylius/admin-bundle/2018-07-09.yaml/blob/master/illuminate/auth/CVE-2017-9303.yaml/blob/master/illuminate/auth/CVE-2017-14775.yaml/blob/master/illuminate/auth/2014-04-15.yaml/blob/master/illuminate/database/2014-05-20.yaml
- id: ossindex:packagist:illuminate/database:2016-06-05
  title: Risk of mass-assignment vulnerabilities
  description: Risk of mass-assignment vulnerabilities
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4.0.0 <4.0.99"
  - ">=4.1.0 <4.1.29"
  package_manager: packagist
  credit:
  - OSSIndex
  references:
  - http://laravel.com/docs/upgrade#upgrade-4.1.29
  - https://github.com/FriendsOfPHP/security-advisories/blob/master/illuminate/database/2014-05-20.yaml
  source_url: https://ossindex.net/resource/package/8397375826/vulnerabilities
- id: snykio:packagist:illuminate/database:2014-05-20
  title: Mass Assignment
  description: |
    Affected versions of [`illuminate/database`][1] are vulnerable to Mass
    Assignment vulnerabilities.



    [1]: https://packagist.org/packages/illuminate/database
    \nAffected versions of [`illuminate/database`][1] are vulnerable to Mass
    Assignment vulnerabilities.



    [1]: https://packagist.org/packages/illuminate/database
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4 &&  <4.1.29"
  severity: medium
  package_manager: packagist
  cwe:
  - CWE-915
  credit:
  - Unknown
  references:
  - https://laravel.com/docs/5.1/upgrade#upgrade-4.1.29
  source_url: https://snyk.io/vuln/SNYK-PHP-ILLUMINATEDATABASE-70106
