---
- id: friendsofphp:packagist:illuminate/database:2014-05-20
  title: Risk of mass-assignment vulnerabilities
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4.0.0 <4.0.99"
  - ">=4.1.0 <4.1.29"
  package_manager: packagist
  credit:
  - FriendsOfPHP
  references:
  - https://laravel.com/docs/5.1/upgrade#upgrade-4.1.29
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/swiftmailer/swiftmailer/CVE-2016-10074.yaml/blob/master/swiftmailer/swiftmailer/2014-06-13.yaml/blob/master/ezsystems/ezpublish-legacy/2018-02-26-1.yaml/blob/master/ezsystems/ezpublish-legacy/2017-08-22-1.yaml/blob/master/ezsystems/ezpublish-legacy/2017-09-11-1.yaml/blob/master/monolog/monolog/2014-12-29-1.yaml/blob/master/illuminate/auth/CVE-2017-9303.yaml/blob/master/illuminate/auth/2014-04-15.yaml/blob/master/illuminate/auth/CVE-2017-14775.yaml/blob/master/illuminate/encryption/2018-03-30-1.yaml/blob/master/illuminate/database/2014-05-20.yaml
- id: ossindex:packagist:illuminate/database:2016-06-05
  title: Risk of mass-assignment vulnerabilities
  description: Risk of mass-assignment vulnerabilities
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4.0.0 <4.0.99"
  - ">=4.1.0 <4.1.29"
  package_manager: packagist
  credit:
  - OSSIndex
  references:
  - http://laravel.com/docs/upgrade#upgrade-4.1.29
  - https://github.com/FriendsOfPHP/security-advisories/blob/master/illuminate/database/2014-05-20.yaml
  source_url: https://ossindex.net/resource/package/8397375826/vulnerabilities
- id: snykio:packagist:illuminate/database:2014-05-20
  title: Mass Assignment
  description: |
    Affected versions of [`illuminate/database`][1] are vulnerable to Mass
    Assignment vulnerabilities.



    [1]: https://packagist.org/packages/illuminate/database
    \nAffected versions of [`illuminate/database`][1] are vulnerable to Mass
    Assignment vulnerabilities.



    [1]: https://packagist.org/packages/illuminate/database
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4 &&  <4.1.29"
  severity: medium
  package_manager: packagist
  cwe:
  - CWE-915
  credit:
  - Unknown
  references:
  - https://laravel.com/docs/5.1/upgrade#upgrade-4.1.29
  source_url: https://snyk.io/vuln/SNYK-PHP-ILLUMINATEDATABASE-70106
