---
- id: friendsofphp:packagist:illuminate/database:2014-05-20
  title: Risk of mass-assignment vulnerabilities
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4.0.0 <4.0.99"
  - ">=4.1.0 <4.1.29"
  package_manager: packagist
  credit:
  - FriendsOfPHP
  references:
  - https://laravel.com/docs/5.1/upgrade#upgrade-4.1.29
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/paypal/merchant-sdk-php/CVE-2017-6099.yaml/blob/master/socalnick/scn-social-auth/2015-01-15.yaml/blob/master/namshi/jose/2015-03-10.yaml/blob/master/namshi/jose/2015-02-19.yaml/blob/master/gree/jose/2016-08-30.yaml/blob/master/kreait/firebase-php/CVE-2018-1000025.yaml/blob/master/truckersmp/phpwhois/CVE-2015-5243.yaml/blob/master/typo3/neos/2015-11-23.yaml/blob/master/typo3/neos/2015-03-28.yaml/blob/master/typo3/cms-core/2018-07-12-4.yaml/blob/master/typo3/cms-core/2018-07-12-1.yaml/blob/master/typo3/cms-core/2018-07-12-3.yaml/blob/master/typo3/cms-core/2018-07-12-2.yaml/blob/master/typo3/flow/2016-11-01.yaml/blob/master/typo3/flow/CVE-2013-7082.yaml/blob/master/typo3/flow/2012-03-28.yaml/blob/master/typo3/flow/2015-11-23.yaml/blob/master/typo3/cms/2018-07-12-4.yaml/blob/master/typo3/cms/CVE-2014-3944.yaml/blob/master/typo3/cms/2015-07-01-3.yaml/blob/master/typo3/cms/2016-02-23-3.yaml/blob/master/typo3/cms/2016-07-19-6.yaml/blob/master/typo3/cms/2016-04-12-4.yaml/blob/master/typo3/cms/2016-07-19-4.yaml/blob/master/typo3/cms/2017-09-05-3.yaml/blob/master/typo3/cms/2015-07-01-2.yaml/blob/master/typo3/cms/2018-07-12-1.yaml/blob/master/typo3/cms/2016-07-19-7.yaml/blob/master/typo3/cms/2014-12-09-2.yaml/blob/master/typo3/cms/2014-10-22-1.yaml/blob/master/typo3/cms/2016-07-19-3.yaml/blob/master/typo3/cms/2015-12-15-5.yaml/blob/master/typo3/cms/2015-12-15-4.yaml/blob/master/typo3/cms/2016-09-14-2.yaml/blob/master/typo3/cms/2018-07-12-3.yaml/blob/master/typo3/cms/2017-01-03-1.yaml/blob/master/typo3/cms/2016-02-16-2.yaml/blob/master/typo3/cms/CVE-2014-3943.yaml/blob/master/typo3/cms/2015-07-01-4.yaml/blob/master/typo3/cms/2016-02-16-3.yaml/blob/master/typo3/cms/CVE-2014-3941.yaml/blob/master/typo3/cms/2015-09-08-1.yaml/blob/master/typo3/cms/2016-02-23-2.yaml/blob/master/typo3/cms/CVE-2015-5956.yaml/blob/master/typo3/cms/2016-02-16-4.yaml/blob/master/typo3/cms/2016-09-14-1.yaml/blob/master/typo3/cms/2017-09-05-2.yaml/blob/master/typo3/cms/2016-02-16-1.yaml/blob/master/typo3/cms/2016-07-19-5.yaml/blob/master/typo3/cms/2015-07-01-1.yaml/blob/master/typo3/cms/2016-04-12-3.yaml/blob/master/typo3/cms/2016-07-19-1.yaml/blob/master/typo3/cms/2016-05-24-1.yaml/blob/master/typo3/cms/2016-02-23-4.yaml/blob/master/typo3/cms/2014-05-22-1.yaml/blob/master/typo3/cms/2016-02-23-1.yaml/blob/master/typo3/cms/2018-07-12-2.yaml/blob/master/typo3/cms/2015-12-15-1.yaml/blob/master/typo3/cms/2016-04-12-1.yaml/blob/master/typo3/cms/2017-09-05-1.yaml/blob/master/typo3/cms/2014-10-22-2.yaml/blob/master/typo3/cms/2016-04-12-2.yaml/blob/master/typo3/cms/2015-07-01-5.yaml/blob/master/typo3/cms/2015-12-15-3.yaml/blob/master/typo3/cms/2016-11-22-1.yaml/blob/master/typo3/cms/2015-12-15-2.yaml/blob/master/typo3/cms/2015-07-01-6.yaml/blob/master/typo3/cms/2017-09-05-4.yaml/blob/master/typo3/cms/2017-02-28-2.yaml/blob/master/typo3/cms/2014-12-09-1.yaml/blob/master/typo3/cms/CVE-2014-3946.yaml/blob/master/typo3/cms/2016-07-19-2.yaml/blob/master/typo3/cms/2016-11-22-2.yaml/blob/master/typo3/cms/2017-02-28-1.yaml/blob/master/firebase/php-jwt/2015-04-02.yaml/blob/master/illuminate/cookie/2018-08-08-1.yaml/blob/master/illuminate/database/2014-05-20.yaml
- id: ossindex:packagist:illuminate/database:2016-06-05
  title: Risk of mass-assignment vulnerabilities
  description: Risk of mass-assignment vulnerabilities
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4.0.0 <4.0.99"
  - ">=4.1.0 <4.1.29"
  package_manager: packagist
  credit:
  - OSSIndex
  references:
  - http://laravel.com/docs/upgrade#upgrade-4.1.29
  - https://github.com/FriendsOfPHP/security-advisories/blob/master/illuminate/database/2014-05-20.yaml
  source_url: https://ossindex.net/resource/package/8397375826/vulnerabilities
- id: snykio:packagist:illuminate/database:2014-05-20
  title: Mass Assignment
  description: |
    Affected versions of [`illuminate/database`][1] are vulnerable to Mass
    Assignment vulnerabilities.



    [1]: https://packagist.org/packages/illuminate/database
    \nAffected versions of [`illuminate/database`][1] are vulnerable to Mass
    Assignment vulnerabilities.



    [1]: https://packagist.org/packages/illuminate/database
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4 &&  <4.1.29"
  severity: medium
  package_manager: packagist
  cwe:
  - CWE-915
  credit:
  - Unknown
  references:
  - https://laravel.com/docs/5.1/upgrade#upgrade-4.1.29
  source_url: https://snyk.io/vuln/SNYK-PHP-ILLUMINATEDATABASE-70106
