---
- id: snykio:go:github.com/grafana/grafana/pkg/api:CVE-2018-15727
  title: Authentication Bypass
  description: |
    [`github.com/grafana/grafana/pkg/api`][1] is a tool for monitoring and
    metric analytics &amp; dashboards for Graphite, InfluxDB &amp;
    Prometheus &amp; More.

    Affected versions of the package are vulnerable to Authentication
    Bypass. An attacker could generate a valid cookie knowing only a
    username of an `LDAP` or `OAuth` user.



    [1]: https://github.com/grafana/grafana
  affected_package: github.com/grafana/grafana/pkg/api
  vulnerable_versions:
  - "<4.6.4"
  - ">=5.0.0 <5.2.3"
  severity: high
  package_manager: go
  cve:
  - CVE-2018-15727
  cwe:
  - CWE-592
  disclosed_date: 2018-08-19
  created_date: 2018-09-02
  last_modified_date: 2018-09-02
  credit:
  - Unknown
  references:
  - https://github.com/grafana/grafana/commit/df83bf10a225811927644bdf6265fa80bdea9137
  - https://github.com/grafana/grafana/commit/7baecf0d0deae0d865e45cf03e082bc0db3f28c3
  - https://grafana.com/blog/2018/08/29/grafana-5.2.3-and-4.6.4-released-with-important-security-fix/
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGRAFANAGRAFANAPKGAPI-50087
