---
- id: snykio:go:gopkg.in/kubernetes/kubernetes.v0/pkg/registry/pod:174809
  title: Information Exposure
  description: |
    [gopkg.in/kubernetes/kubernetes.v0/pkg/registry/pod][1] is a package
    that provides Registry interface and it\'s RESTStorage implementation
    for storing Pod api objects.

    Affected versions of this package are vulnerable to Information
    Exposure. Allows remote attackers to read arbitrary pod logs via a
    container name.



    [1]: https://godoc.org/gopkg.in/kubernetes/kubernetes.v0/pkg/registry/pod
  affected_package: gopkg.in/kubernetes/kubernetes.v0/pkg/registry/pod
  vulnerable_versions:
  - "<1.2.0-alpha.5"
  severity: medium
  package_manager: go
  cve:
  - CVE-2015-7528
  cwe:
  - CWE-200
  disclosed_date: 2015-11-28
  created_date: 2015-11-28
  last_modified_date: 2015-11-28
  credit:
  - Unknown
  references:
  - https://github.com/kubernetes/kubernetes/commit/afd56495a1052a3387b81df1786a8d0f51bc8671
  - https://github.com/kubernetes/kubernetes/pull/17886
  - https://github.com/kubernetes/kubernetes/releases/tag/v1.2.0-alpha.5
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GOPKGINKUBERNETESKUBERNETESV0PKGREGISTRYPOD-174809
