---
- id: snykio:pypi:products-ploneformgen:42100
  title: Cross-site Scripting (XSS)
  description: |+
    [products-ploneformgen][1] provides a generic Plone form generator. Use
    it to build simple, one-of-a-kind, web forms that save or mail form
    input.

    Affected versions of this package are vulnerable to Cross-site Scripting
    (XSS) attacks. It could be exploited by users with the ability to create
    forms.



    [1]: https://pypi.org/project/Products.PloneFormGen/
    \nCross-Site Scripting (XSS) attacks occur when an attacker tricks a
    user’s browser to execute malicious JavaScript code in the context of a
    victim’s domain. Such scripts can steal the user’s session cookies for
    the domain, scrape or modify its content, and perform or modify actions
    on the user’s behalf, actions typically blocked by the browser’s Same
    Origin Policy.

    These attacks are possible by escaping the context of the web
    application and injecting malicious scripts in an otherwise trusted
    website. These scripts can introduce additional attributes (say, a
    \"new\" option in a dropdown list or a new link to a malicious site) and
    can potentially execute code on the clients side, unbeknown to the
    victim. This occurs when characters like `<` `>` `"` `'` are not escaped
    properly.

    There are a few types of XSS:

    * **Persistent XSS** is an attack in which the malicious code persists
      into the web app’s database.
    * **Reflected XSS** is an which the website echoes back a portion of the
      request. The attacker needs to trick the user into clicking a
      malicious link (for instance through a phishing email or malicious JS
      on another page), which triggers the XSS attack.
    * **DOM-based XSS** is an that occurs purely in the browser when
      client-side JavaScript echoes back a portion of the URL onto the page.
      DOM-Based XSS is notoriously hard to detect, as the server never gets
      a chance to see the attack taking place.

  affected_package: products-ploneformgen
  vulnerable_versions:
  - "< 1.8.1"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-79
  disclosed_date: 2016-05-01
  created_date: 2018-05-08
  last_modified_date: 2018-05-08
  credit:
  - Unknown
  references:
  - https://pypi.org/project/Products.PloneFormGen/1.8.1/
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PRODUCTSPLONEFORMGEN-42100
