---
- id: snykio:pypi:products.cmfformcontroller:CVE-2016-7137
  title: Open Redirect
  description: |
    [`products.cmfformcontroller`][1] is a CMFFormController provides a form
    validation mechanism for CMF.

    Affected versions of this project are vulnerable to Open Redirection.
    Multiple open redirect vulnerabilities in Plone CMS 5.x through 5.0.6,
    4.x through 4.3.11, and 3.3.x through 3.3.6 allow remote attackers to
    redirect users to arbitrary web sites and conduct phishing attacks via a
    URL in the referer parameter to (1)
    %2b%2bgroupdashboard%2b%2bplone.dashboard1%2bgroup/%2b/portlets.Actions
    or (2) folder/%2b%2bcontextportlets%2b%2bplone.footerportlets/%2b
    /portlets.Actions or the (3) came\_from parameter to /login\_form.



    [1]: https://pypi.python.org/pypi/products.cmfformcontroller
  affected_package: products.cmfformcontroller
  vulnerable_versions:
  - "< 3.1.3"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2016-7137
  cwe:
  - CWE-601
  disclosed_date: 2016-07-18
  created_date: 2016-07-18
  last_modified_date: 2016-07-18
  credit:
  - Sebastian Perez
  references:
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-7137
  - https://plone.org/security/hotfix/20160830/open-redirection-in-plone
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PRODUCTSCMFFORMCONTROLLER-40418
