---
- id: snykio:pypi:products.plonepas:2009-04-23
  title: User Impersonation
  description: |
    [products.plonepas][1] modifies the PluggableAuthService for use by
    Plone.

    Affected versions of this package are vulnerable to User Impersonation.
    It does not properly handle the login form, which allows remote
    authenticated users to acquire the identity of an arbitrary user.



    [1]: https://pypi.org/project/Products.PlonePAS/
    \n[products.plonepas][1] modifies the PluggableAuthService for use by
    Plone.

    Affected versions of this package are vulnerable to User Impersonation.
    It does not properly handle the login form, which allows remote
    authenticated users to acquire the identity of an arbitrary user.



    [1]: https://pypi.org/project/Products.PlonePAS/
    \n[products.plonepas][1] modifies the PluggableAuthService for use by
    Plone.

    Affected versions of this package are vulnerable to User Impersonation.
    It does not properly handle the login form, which allows remote
    authenticated users to acquire the identity of an arbitrary user.



    [1]: https://pypi.org/project/Products.PlonePAS/
  affected_package: products.plonepas
  vulnerable_versions:
  - "< 3.9"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2009-0662
  cwe:
  - CWE-287
  credit:
  - Unknown
  references:
  - https://nvd.nist.gov/vuln/detail/CVE-2009-0662
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PRODUCTSPLONEPAS-42155
