---
- id: snykio:pypi:products.poi:40596
  title: Information Exposure
  description: |
    [`products_poi`][1] is a friendly issue tracker.

    Affected versions of this package are vulnerable to Information
    Exposure.



    [1]: https://pypi.python.org/pypi/products_poi
  affected_package: products.poi
  vulnerable_versions:
  - "< 2.2.3"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-200
  disclosed_date: 2013-04-12
  created_date: 2013-04-12
  last_modified_date: 2013-04-12
  credit:
  - Luca Fabbri
  references:
  - https://github.com/collective/Products.Poi/commit/07b4620a4ebc00dcb2bba4bd36ff3bc13eb2d05f
  - https://github.com/collective/Products.Poi/pull/8
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PRODUCTSPOI-40596
