---
- id: snykio:pypi:products.cmfeditions:40253
  title: Sub-object Permissions
  description: |
    [`products.cmfeditions`][1] is a Versioning for Plone.

    The CMFEditions component 2.x in Plone 4.0.x through 4.0.9, 4.1, and 4.2
    through 4.2a2 does not prevent the KwAsAttributes classes from being
    publishable, which allows remote attackers to access sub-objects via
    unspecified vectors, a different vulnerability than CVE-2011-3587.



    [1]: https://pypi.python.org/pypi/products.cmfeditions
  affected_package: products.cmfeditions
  vulnerable_versions:
  - ">= 2 < 2.2.2"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2011-4030
  cwe:
  - CWE-264
  disclosed_date: 2011-10-04
  created_date: 2011-10-04
  last_modified_date: 2011-10-04
  credit:
  - Unknown
  references:
  - https://github.com/plone/Products.CMFEditions/commit/d55add52e5900967c8cc78becc6790048f02015b
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2011-4030
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PRODUCTSCMFEDITIONS-40253
