---
- id: snykio:pypi:pyxmlsecurity:40593
  title: XML Signature Wrapping
  description: |
    [`pyxmlsecurity`][1] is a pure Python XML Security.

    Affected versions of this package are vulnerable to XML Signature
    Wrapping via the `verify` function.



    [1]: https://pypi.python.org/pypi/pyxmlsecurity
  affected_package: pyxmlsecurity
  vulnerable_versions:
  - ">= 0.7 < 0.9"
  severity: medium
  package_manager: pypi
  cwe:
  - CWE-347
  disclosed_date: 2013-06-20
  created_date: 2013-06-20
  last_modified_date: 2013-06-20
  credit:
  - Unknown
  references:
  - https://github.com/leifj/pyXMLSecurity/commit/3fe6c3b56e1404121887f74a0db196cc19c011fa
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PYXMLSECURITY-40593
